src/App.tsx
src/components/GridBoard.tsx
src/pages/BoardDetails.tsx
src/pages/Mypage.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
---
**이슈 번호**: N/A
---
- 마이페이지 UI 구현
- GridBoard 컴포넌트 추가
- 보드 상세페이지 이동
---
-   [ ] 네
-   [x] 아니오
---

[Feat] 마이페이지 UI 구현

---

.eslintrc
.prettierrc
eslint.config.mjs
package-lock.json
package.json
src/components/MasonryLayout.tsx
src/firebase.tsx
src/pages/Mypage.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
-   [x] 코드 스타일 수정 (포맷팅, 로컬 변수 등)
---
**이슈 번호**: N/A
---
---
-   [ ] 네
-   [x] 아니오
---

Feat/my page + ESLint와 Prettier 설정

---

package-lock.json
package.json
src/App.tsx
src/components/Header.tsx
src/pages/Login.tsx
src/pages/Signup.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
---
header ui구현, 글로벌 컴포넌트로 app.tsx 추가, icons설치 build확인
**이슈 번호**: N/A
#5 
---
---
-   [x] 네
-   [ ] 아니오
---

[Feat] 헤더 ui 구현

---

package-lock.json
package.json
src/components/GridBoard.tsx
src/pages/Mypage.tsx
tsconfig.json

---
PR 유형을 선택해주세요
-   [x] 버그 수정
---
**이슈 번호**: N/A
---
---
-   [ ] 네
-   [x] 아니오
---

[Feat] my page

---

src/components/NavBar.tsx

---
PR 유형을 선택해주세요
-   [x] 버그 수정
---
**이슈 번호**: N/A
---
---
-   [ ] 네
-   [x] 아니오
---

Fix: empty arrow function error 해결

---

src/components/Header.tsx
src/features/authSlice.tsx
src/pages/Login.tsx
src/pages/Signup.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
---
**이슈 번호**: N/A
#18 
---
---
-   [x] 네
-   [ ] 아니오
---

[Feat] firebase 로그인, 회원가입 코드 수정

---

src/components/Profile.tsx

---
PR 유형을 선택해주세요
-   [x] 버그 수정
-   [x] 기타... 설명해주세요: UI 수정
---
**이슈 번호**: N/A
---
---
-   [ ] 네
-   [x] 아니오
---

[Feat] 프로필 페이지 수정

---

src/App.tsx
src/components/EditProfile.tsx
src/components/NavBar.tsx
src/components/Profile.tsx
src/pages/Settings.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
---
**이슈 번호**: N/A
---
---
-   [ ] 네
-   [x] 아니오
---

[Feat] 설정 페이지 탭 레이아웃

---

src/App.tsx
src/components/Header.tsx
src/components/Profile.tsx
src/hooks/useCurrentUserUid.ts
src/pages/AllPinsPage.tsx
src/pages/Mypage.tsx
src/pages/UserProfilePage.tsx

---
PR 유형을 선택해주세요
-   [x] 버그 수정
-   [x] 리팩토링 (기능이나 API의 변경 없이 코드 개선)
---
**이슈 번호**: N/A
---
- 프로필 페이지에서 '모든 핀' 눌렀을 때 상세페이지
- 현재 로그인 한 사용자의 UID를 가져오는 로직 추가
- 현재 로그인 한 사용자 기준으로 팔로우 상태가 반영되지 않던 문제 해결
- 마이페이지 제거 및 프로필 페이지로 통합
---
-   [ ] 네
-   [x] 아니오
---

[Feat] 프로필 페이지 기능 추가 및 개선

---

src/components/ProfileComment.tsx
src/pages/PinPage.tsx
src/utils/firestoreUtils.ts

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
---
**이슈 번호**: N/A
---
- 댓글 작성 기능 추가
---
-   [ ] 네
-   [x] 아니오
---

[Feat] 댓글 작성 기능

---

src/hooks/useDebounce.ts
src/pages/Signup.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
---
**이슈 번호**: N/A
#37 
---
- 회원가입 창에서 id 중복검사
---
-   [x] 네
-   [ ] 아니오
---

[Feat] 회원가입 아이디 중복 검사

---

src/App.tsx
src/components/NavBar.tsx
src/pages/PhotoEditPage.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
-   [x] 리팩토링 (기능이나 API의 변경 없이 코드 개선)
---
**이슈 번호**: N/A
---
---
-   [x] 네
-   [ ] 아니오
---

[Feat] 핀 꾸미기 기능

---

src/App.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
---
**이슈 번호**: N/A
---
---
-   [ ] 네
-   [ ] 아니오
---

[Feat] 핀 꾸미기 기능 구현 수정

---

src/components/AccountManagement.tsx

---
PR 유형을 선택해주세요
-   [x] 버그 수정
---
**이슈 번호**: N/A
---
- 현재 비밀번호 입력받는 폼 개별 분리하였습니다.
---
-   [ ] 네
-   [ ] 아니오
---

[Feat] 현재 비밀번호 입력 개별 분리

---

src/components/AccountManagement.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
---
**이슈 번호**: N/A
---
- 계정삭제를 한 이후 메인페이지로 이동
- firestore에 사용자 데이터 삭제 기능 추가
---
-   [x] 네
-   [ ] 아니오
---

[Feat] 계정 삭제 로직 변경

---

src/pages/PinPage.tsx

---
PR 유형을 선택해주세요
-   [x] 버그 수정
---
**이슈 번호**: N/A
---
---
-   [x] 네
-   [ ] 아니오
---

[fix]SaveModal Type 수정

---

src/App.tsx
src/features/authSlice.tsx
src/pages/Login.tsx
src/pages/Signup.tsx

---
PR 유형을 선택해주세요
-   [x] 버그 수정
---
**이슈 번호**: N/A
---
---
-   [ ] 네
-   [ ] 아니오
---

[Fix] 로그인 회원가입 오류 수정

---

.github/workflow/lint.yml

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
-   [x] 코드 스타일 수정 (포맷팅, 로컬 변수 등)
---
**이슈 번호**: N/A
---
Lint Pipeline 설정 추가
---
-   [ ] 네
-   [x] 아니오
---

Docs: Lint Pipeline 설정 추가

---

src/components/Modal.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
-   [ ] 기타... 설명해주세요: design 변경
---
**이슈 번호**: N/A
---
---
-   [ ] 네
-   [x] 아니오
---

Design : 새 메세지 UI 변경

---

src/App.tsx
src/features/authSlice.tsx

---
PR 유형을 선택해주세요
-   [x] 버그 수정
---
**이슈 번호**: N/A
#59 
---
---
-   [x] 네
-   [ ] 아니오
---

[Fix] 새로 고침 시 페이지 유지

---

src/components/Home/Head.jsx
src/components/Home/Section.tsx
src/pages/LandingPage.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
-   [] 코드 스타일 수정 (포맷팅, 로컬 변수 등)
-   [] 리팩토링 (기능이나 API의 변경 없이 코드 개선)
-   [x] UI개선
---
**이슈 번호**: #64 
---
---
-   [x] 네
-   [ ] 아니오
---

Design: 랜딩페이지 반응형

---

src/App.tsx
src/components/MasonryLayout.tsx
src/components/Profile.tsx
src/components/ScrollTop.tsx
src/pages/AllPinsPage.tsx
src/pages/BoardDetails.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
---
**이슈 번호**: #63 
---
- 마이페이지에서 핀 클릭 시 핀 상세페이지로 이동
- 보드 상세페이지에서 핀 클릭 시 핀 상세페이지로 이동
- 페이지 이동 시 스크롤 맨 위로
- 로딩 UI 변경
---
-   [ ] 네
-   [x] 아니오
---

[Feat] 저장된 핀 클릭시 상세페이지 이동

---

src/components/Header.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
---
**이슈 번호**: N/A
#68 
---
---
-   [x] 네
-   [ ] 아니오
---

Design : 헤더 검색바 UI 변경

---

src/components/StoryList.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
-   [x] 기타: UI 개선
---
**이슈 번호**: #70 
---
- 기존에는 자신의 프로필을 클릭해야 자신의 스토리 활성화 여부를 확인할 수 있었음
- 스토리가 업로드되면 프로필에 파란색 테두리로 시각적 표시를 해서 사용자가 업로드 상태를 인지할 수 있도록 수정
---
-   [ ] 네
-   [x] 아니오
---

[Design] 스토리 활성화 여부 시각적 표시

---

package-lock.json
package.json
src/App.tsx
src/components/Header.tsx
src/pages/Login.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
---
**이슈 번호**: N/A
#61 
---
---
-   [x] 네
-   [ ] 아니오
---

[Feat] toast 로그인 ui 구현

---

src/components/Header.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
---
**이슈 번호**: N/A
#73 
---
---
-   [x] 네
-   [ ] 아니오
---

[Design] 로그아웃 상태에서 검색바 비활성화

---

src/pages/CreateStory.tsx
src/pages/StoryPage.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
---
**이슈 번호**: #75 
---
- 스토리 삭제 기능 추가
- 스토리 생성 및 삭제 시 alert 대신 toast UI 적용
---
-   [ ] 네
-   [x] 아니오
---

[Feat] 스토리 삭제 기능

---

src/components/EditProfile.tsx
src/components/Header.tsx
src/features/authSlice.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
---
**이슈 번호**: N/A
#77 
---
---
-   [x] 네
-   [ ] 아니오
---

[Feat] 상단 네비게이션 프로필 상태

---

src/components/EditProfile.tsx
src/components/Header.tsx
src/features/authSlice.tsx

---
PR 유형을 선택해주세요
-   [x] 버그 수정
---
**이슈 번호**: N/A
#83 
---
---
-   [x] 네
-   [ ] 아니오
---

[Fix] 헤더 프로필 상태

---

src/components/EditProfile.tsx
src/components/UserTag.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
-   [x] 기타... : UI 개선
---
**이슈 번호**: #80 
---
- 프로필 수정 완료 시 toast UI를 통해 알림 메시지 전달
- 프로필 사진에 긴 이미지 업로드 시 찌그러지는 현상 수정
---
-   [ ] 네
-   [x] 아니오
---

[Design] 프로필 수정 완료 시 알림 메시지 전달

---

package-lock.json
package.json
src/App.tsx
src/components/Header.tsx
src/components/MasonryLayout.tsx
src/components/Pin.tsx
src/components/Profile.tsx
src/pages/AllPinsPage.tsx
src/pages/PinBuilder.tsx
src/pages/SearchResultPage.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
-   [x] 리팩토링 (기능이나 API의 변경 없이 코드 개선)
---
**이슈 번호**: N/A
#81 
---
---
-   [x] 네
-   [ ] 아니오
---

[Feat] 검색 기능 구현

---

src/components/Pin.tsx
src/components/SaveDropdown.tsx
src/features/boardSlice.tsx

---
PR 유형을 선택해주세요
-   [x] 버그 수정
---
**이슈 번호**: #87 
---
핀 저장 시 user의 savedPins에 추가해 모든 핀에서도 저장한 핀을 볼 수 있음
---
-   [ ] 네
-   [x] 아니오
---

[Fix] 저장 시 모든 핀에도 추가되도록 수정

---

src/App.tsx
src/components/Header.tsx
src/components/Pin.tsx
src/features/searchSlice.tsx
src/store.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
---
**이슈 번호**: N/A
#91 
---
---
-   [x] 네
-   [ ] 아니오
---

[Feat] 검색어 유지 리셋

---

src/components/Home/ShareModal.tsx
src/components/Pin.tsx
src/components/PinterestLayout.tsx

---
PR 유형을 선택해주세요
-   [x] 버그 수정
---
**이슈 번호**: #94  #93 
---
---
-   [x] 네
-   [ ] 아니오
---

[Fix] 링크 버튼 클릭 / 페이지 이동 제한 

---

src/components/Modal.tsx
src/components/Profile.tsx

---
PR 유형을 선택해주세요
-   [ ] 버그 수정
---
**이슈 번호**: #97 , #98 
---
- 다른 유저의 프로필에서 메시지 버튼을 눌러 해당 유저에게 메시지 보내기
- 프로필 공유 기능 중, 다른 유저에게 보내기 버튼 클릭 시 메시지로 프로필 링크 보내기
---
-   [ ] 네
-   [x] 아니오
---

[Feat] 다른 유저 프로필에서 메시지 전송 및 프로필 보내기

---

src/components/Home/ShareModal.tsx
src/components/Modal.tsx
src/components/Pin.tsx
src/components/PinterestLayout.tsx
src/components/Profile.tsx

---
PR 유형을 선택해주세요
-   [x] 버그 수정
---
**이슈 번호**: #100 
---
---
-   [x] 네
-   [ ] 아니오
---

[Fix]모달 창 유지 

---

src/components/BoardCreateModal.tsx
src/components/Profile.tsx
src/components/SaveDropdown.tsx
src/components/SearchDropdown.tsx
src/components/SimpleBoardCreateModal.tsx
src/pages/PinBuilder.tsx
src/pages/PinPage.tsx

---
PR 유형을 선택해주세요
-   [x] 버그 수정
---
**이슈 번호**: N/A
---
---
-   [ ] 네
-   [x] 아니오
---

Error haeun

---

.firebaserc
firebase.json
package-lock.json
package.json
server/server.mjs
src/components/Pin.tsx
src/pages/PinPage.tsx

---
PR 유형을 선택해주세요
-   [x] 버그 수정
---
**이슈 번호**: N/A
#103 
---
---
-   [ ] 네
-   [ ] 아니오
---

[Fix] cors 이미지 다운로드

---

src/components/BoardCreateModal.tsx
src/components/InviteModal.tsx
src/components/MergeModal.tsx
src/components/Profile.tsx
src/components/SaveDropdown.tsx
src/components/SimpleBoardCreateModal.tsx
src/pages/BoardDetails.tsx

---
PR 유형을 선택해주세요
-   [x] 버그 수정
---
**이슈 번호**: #105 
---
- 보드 만들기 모달창을 열 때 NavBar와 Header가 검은 배경 위에 표시되는 문제 해결
- stacking context 문제 해결
---
-   [ ] 네
-   [x] 아니오
---

[Fix] stacking context 문제 해결
